on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: build flakes
      uses: Reasonable-Solutions/friendly-parakeet@master
      with:
        packages:
          - ripgrep
          - ponysay
          - default
